language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "lts/*"
script: KARMA_OPTS="--browsers Firefox,PhantomJS" make -e test
before_script:
  - export DISPLAY=:99.0        
  - sh -e /etc/init.d/xvfb start
